server {
    listen 80;
    return 301 https://$host:8890$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/nodino.crt;
    ssl_certificate_key /etc/nginx/certs/nodino.key;

    client_max_body_size 25m;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://host.docker.internal:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 180s;
        proxy_request_buffering off;
    }
}
